version: "3"
services:
  react-app:
    image: react-prod
    build: ../Front_End/client
    stdin_open: true
    ports:
      - "8080:80"
    networks:
      - mern-app
  api-server:
    image: api-server
    build: .
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge