FROM node:14.14.0-alpine

ENV MONGO_URI=mongodb+srv://dev_fantasy_admin:AtlasOfTheWorld7@cluster0.ektda.mongodb.net/Fantasy?retryWrites=true&w=majority

WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . ./
EXPOSE 5000

CMD ["npm", "run", "start"]